name = "JuDGE"
uuid = "7600667b-db04-5866-8f94-e5ff75fe7256"
authors = ["Regan Baucke, Anthony Downward"]
version = "0.1.2"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
DataStructures = "0.18"
JuMP = "0.21"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DelimitedFiles", "GLPK", "Random", "Test"]
